version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./user_interface
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app-network

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
